FROM ubuntu:22.04

RUN apt-get update && apt-get install python3 -y && apt-get install nano -y && apt-get install net-tools -y && apt-get install iproute2 -y 
RUN apt-get update && apt-get install python3-pip -y
RUN pip install pyzmq
